# Generated by Django 6.1.1 on 2026-09-06 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pas', '0002_pengajuanpas_dokumenpengajuan_statusriwayat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('lokasi', models.CharField(max_length=255)),
                ('kuota', models.PositiveIntegerField(default=20)),
                ('status', models.CharField(choices=[('OPEN', 'Buka'), ('FULL', 'Penuh'), ('CLOSED', 'Tutup'), ('CANCELLED', 'Dibatalkan')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jadwal Screening',
                'verbose_name_plural': 'Jadwal Screening',
                'ordering': ['tanggal', 'jam_mulai'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_booking', models.CharField(blank=True, max_length=30, unique=True)),
                ('nomor_antrian', models.PositiveIntegerField(default=0)),
                ('waktu_booking', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('BOOKED', 'Terbooking'), ('CHECKED_IN', 'Check-in'), ('PROCESS', 'Proses'), ('COMPLETED', 'Selesai'), ('NO_SHOW', 'Tidak Hadir'), ('CANCELLED', 'Dibatalkan')], default='BOOKED', max_length=20)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pas.pengajuanpas')),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='screening.screeningschedule')),
            ],
            options={
                'verbose_name': 'Booking Screening',
                'verbose_name_plural': 'Booking Screening',
                'ordering': ['jadwal', 'nomor_antrian'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_screening', models.DateTimeField(auto_now_add=True)),
                ('hasil', models.CharField(choices=[('PASSED', 'Lulus'), ('FAILED', 'Tidak Lulus')], max_length=10)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hasil', to='screening.screeningbooking')),
                ('petugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hasil_screening', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hasil Screening',
                'verbose_name_plural': 'Hasil Screening',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='screeningbooking',
            constraint=models.UniqueConstraint(fields=('jadwal', 'nomor_antrian'), name='unique_antrian_per_jadwal'),
        ),
    ]
