# Generated by Django 6.1.1 on 2026-09-11 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('QRIS', 'QRIS'), ('VIRTUAL_ACCOUNT', 'Virtual Account'), ('BANK_TRANSFER', 'Transfer Bank'), ('E_WALLET', 'E-Wallet'), ('CARD', 'Kartu'), ('OTC', 'Convenience Store / OTC'), ('MANUAL_TRANSFER', 'Transfer Manual'), ('CASH', 'Tunai'), ('OTHER', 'Lainnya')], max_length=30)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('configuration', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Metode Pembayaran',
                'verbose_name_plural': 'Metode Pembayaran',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_invoice', models.CharField(blank=True, max_length=30, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('biaya_admin', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('tanggal_terbit', models.DateTimeField(auto_now_add=True)),
                ('tanggal_jatuh_tempo', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNPAID', 'Belum Dibayar'), ('PENDING', 'Menunggu'), ('PAID', 'Lunas'), ('PARTIALLY_PAID', 'Dibayar Sebagian'), ('EXPIRED', 'Kedaluwarsa'), ('CANCELLED', 'Dibatalkan'), ('REFUNDED', 'Direfund')], default='DRAFT', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pengajuan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='pas.pengajuan')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255)),
                ('merchant_reference', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('status', models.CharField(choices=[('CREATED', 'Dibuat'), ('PENDING', 'Menunggu'), ('PAID', 'Lunas'), ('FAILED', 'Gagal'), ('EXPIRED', 'Kedaluwarsa'), ('CANCELLED', 'Dibatalkan'), ('REFUNDED', 'Direfund'), ('PARTIALLY_REFUNDED', 'Refund Sebagian')], default='CREATED', max_length=30)),
                ('payment_url', models.URLField(blank=True)),
                ('qr_string', models.TextField(blank=True)),
                ('va_number', models.CharField(blank=True, max_length=100)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to='pembayaran.invoice')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaksi', to='pembayaran.paymentmethod')),
            ],
            options={
                'verbose_name': 'Transaksi Pembayaran',
                'verbose_name_plural': 'Transaksi Pembayaran',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PembayaranManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bukti', models.FileField(upload_to='pembayaran/bukti/')),
                ('catatan', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaksi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual', to='pembayaran.paymenttransaction')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pembayaran Manual',
                'verbose_name_plural': 'Pembayaran Manual',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_refund_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('REQUESTED', 'Diminta'), ('APPROVED', 'Disetujui'), ('PROCESSED', 'Diproses'), ('REFUNDED', 'Direfund'), ('REJECTED', 'Ditolak')], default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_requested', to=settings.AUTH_USER_MODEL)),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='pembayaran.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refund',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_event_id', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('signature', models.TextField(blank=True)),
                ('processing_status', models.CharField(choices=[('RECEIVED', 'Diterima'), ('PROCESSED', 'Diproses'), ('DUPLICATE', 'Duplikat'), ('FAILED', 'Gagal')], default='RECEIVED', max_length=30)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='pembayaran.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Log Webhook',
                'verbose_name_plural': 'Log Webhook',
                'ordering': ['-received_at'],
            },
        ),
    ]
