# Generated by Django 6.1.1 on 2026-09-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('KOMERSIL', 'Komersil'), ('OPERASI', 'Operasi'), ('AOCH', 'AOCH'), ('AVSEC', 'Avsec'), ('PEMOHON', 'Pemohon')], default='PEMOHON', max_length=30),
        ),
    ]
