# Generated by Django 6.1.1 on 2026-09-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_awal',
            field=models.CharField(blank=True, help_text='Password sementara yang bisa dilihat pembuat akun lewat tombol Lihat. Dihapus otomatis saat user berhasil login.', max_length=128, verbose_name='Password awal'),
        ),
    ]
