# Generated by Django 6.1.1 on 2026-09-06 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pas', '0002_pengajuanpas_dokumenpengajuan_statusriwayat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('role', models.CharField(choices=[('ADMIN_PAS', 'Admin PAS'), ('VERIFIKATOR', 'Verifikator'), ('SECURITY', 'Security / AVSEC'), ('APPROVER', 'Pejabat Berwenang'), ('MANAGEMENT', 'Management')], max_length=30)),
                ('nama', models.CharField(blank=True, max_length=255)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Langkah Approval',
                'verbose_name_plural': 'Langkah Approval',
                'ordering': ['workflow', 'level'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('role', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to=settings.AUTH_USER_MODEL)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='pas.pengajuanpas')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='approval.approvalstep')),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approval',
                'ordering': ['pengajuan', 'level'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('aktif', models.BooleanField(default=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('jenis_pas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_approval', to='pas.jenispas')),
            ],
            options={
                'verbose_name': 'Workflow Approval',
                'verbose_name_plural': 'Workflow Approval',
                'ordering': ['nama'],
            },
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approval.approvalworkflow'),
        ),
    ]
