# Generated by Django 6.1.1 on 2026-09-06 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAkses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('status_aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Area Akses',
                'verbose_name_plural': 'Area Akses',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='JenisPAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('masa_berlaku_hari', models.PositiveIntegerField(default=30, help_text='Masa berlaku dalam hari')),
                ('biaya', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('butuh_screening', models.BooleanField(default=True)),
                ('butuh_approval', models.BooleanField(default=True)),
                ('status_aktif', models.BooleanField(default=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Jenis PAS',
                'verbose_name_plural': 'Jenis PAS',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Persyaratan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kode', models.CharField(max_length=50)),
                ('deskripsi', models.TextField(blank=True)),
                ('wajib', models.BooleanField(default=True)),
                ('format_file', models.CharField(blank=True, help_text='Ekstensi yang diizinkan, pisahkan koma (jpg,png,pdf)', max_length=100)),
                ('max_size', models.PositiveIntegerField(default=2, help_text='Ukuran maksimal file (MB)')),
                ('aktif', models.BooleanField(default=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('jenis_pas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persyaratan', to='pas.jenispas')),
            ],
            options={
                'verbose_name': 'Persyaratan',
                'verbose_name_plural': 'Persyaratan',
                'ordering': ['jenis_pas', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nominal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('keterangan', models.TextField(blank=True)),
                ('status_aktif', models.BooleanField(default=True)),
                ('jenis_pas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarif', to='pas.jenispas')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarif',
                'ordering': ['nama'],
            },
        ),
    ]
