# Generated by Django 6.1.1 on 2026-09-11 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarHitam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('ORANG', 'Nama Orang'), ('PERUSAHAAN', 'Nama Perusahaan')], default='PERUSAHAAN', max_length=20)),
                ('nama', models.CharField(max_length=255)),
                ('alasan', models.TextField(blank=True)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daftar Hitam',
                'verbose_name_plural': 'Daftar Hitam',
                'ordering': ['tipe', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_layanan', models.CharField(max_length=50, unique=True)),
                ('nama_layanan', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True)),
                ('minimal_pendamping', models.PositiveIntegerField(default=0)),
                ('maksimal_pendamping', models.PositiveIntegerField(default=0, help_text='0 berarti tidak terbatas')),
                ('jenis_tarif', models.CharField(choices=[('FIXED', 'Harga Tetap'), ('PER_PENDAMPING', 'Per Pendamping'), ('PER_HARI', 'Per Hari'), ('PER_PENDAMPING_PER_HARI', 'Per Pendamping / Hari'), ('BY_REQUEST', 'By Request')], default='PER_PENDAMPING_PER_HARI', max_length=30)),
                ('harga', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('satuan', models.CharField(blank=True, max_length=50)),
                ('aktif', models.BooleanField(default=True)),
                ('tanggal_mulai_berlaku', models.DateField(blank=True, null=True)),
                ('tanggal_akhir_berlaku', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Layanan',
                'verbose_name_plural': 'Layanan',
                'ordering': ['nama_layanan'],
            },
        ),
        migrations.CreateModel(
            name='Pengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_pengajuan', models.CharField(blank=True, max_length=30, unique=True)),
                ('tanggal_pelaksanaan', models.DateField()),
                ('waktu_kedatangan', models.TimeField(blank=True, null=True)),
                ('nomor_penerbangan', models.CharField(blank=True, max_length=50)),
                ('asal_penerbangan', models.CharField(blank=True, max_length=100)),
                ('tujuan', models.CharField(blank=True, max_length=255, verbose_name='Tujuan/Instansi')),
                ('jumlah_tamu', models.PositiveIntegerField(default=0)),
                ('jumlah_pendamping', models.PositiveIntegerField(default=0)),
                ('keterangan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DIAJUKAN', 'Diajukan'), ('VERIFIKASI_KOMERSIL', 'Verifikasi Komersil'), ('REVISI_PEMOHON', 'Revisi Pemohon'), ('DISETUJUI_KOMERSIL', 'Disetujui Komersil'), ('MENUNGGU_OPERASI', 'Menunggu Operasi'), ('DITOLAK_OPERASI', 'Ditolak Operasi'), ('DISETUJUI_OPERASI', 'Disetujui Operasi'), ('MENUNGGU_PEMBAYARAN', 'Menunggu Pembayaran'), ('DIBAYAR', 'Sudah Dibayar'), ('SIAP_DILAKSANAKAN', 'Siap Dilaksanakan'), ('DILAKSANAKAN', 'Dilaksanakan'), ('ACKNOWLEDGED_AOCH', 'Acknowledged AOCH'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan')], default='DRAFT', max_length=30)),
                ('catatan', models.TextField(blank=True)),
                ('harga_satuan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jenis_tarif', models.CharField(blank=True, max_length=30)),
                ('satuan', models.CharField(blank=True, max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pengajuan', to='pas.layanan')),
                ('pemohon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengajuan',
                'verbose_name_plural': 'Pengajuan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Persyaratan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kode', models.CharField(max_length=50)),
                ('deskripsi', models.TextField(blank=True)),
                ('wajib', models.BooleanField(default=True)),
                ('format_file', models.CharField(blank=True, help_text='Ekstensi diizinkan, pisahkan koma (jpg,png,pdf)', max_length=100)),
                ('max_size', models.PositiveIntegerField(default=2, help_text='Ukuran maksimal (MB)')),
                ('aktif', models.BooleanField(default=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persyaratan', to='pas.layanan')),
            ],
            options={
                'verbose_name': 'Persyaratan',
                'verbose_name_plural': 'Persyaratan',
                'ordering': ['layanan', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='DokumenPengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pengajuan/dokumen/')),
                ('nomor_dokumen', models.CharField(blank=True, max_length=100)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('status_verifikasi', models.CharField(choices=[('UPLOADED', 'Diunggah'), ('VALID', 'Valid'), ('INVALID', 'Tidak Valid'), ('REVISION_REQUIRED', 'Perlu Revisi')], default='UPLOADED', max_length=30)),
                ('catatan_verifikator', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumen_verified', to=settings.AUTH_USER_MODEL)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='pas.pengajuan')),
                ('persyaratan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='pas.persyaratan')),
            ],
            options={
                'verbose_name': 'Dokumen Pengajuan',
                'verbose_name_plural': 'Dokumen Pengajuan',
                'ordering': ['persyaratan__urutan'],
            },
        ),
        migrations.CreateModel(
            name='StatusRiwayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DIAJUKAN', 'Diajukan'), ('VERIFIKASI_KOMERSIL', 'Verifikasi Komersil'), ('REVISI_PEMOHON', 'Revisi Pemohon'), ('DISETUJUI_KOMERSIL', 'Disetujui Komersil'), ('MENUNGGU_OPERASI', 'Menunggu Operasi'), ('DITOLAK_OPERASI', 'Ditolak Operasi'), ('DISETUJUI_OPERASI', 'Disetujui Operasi'), ('MENUNGGU_PEMBAYARAN', 'Menunggu Pembayaran'), ('DIBAYAR', 'Sudah Dibayar'), ('SIAP_DILAKSANAKAN', 'Siap Dilaksanakan'), ('DILAKSANAKAN', 'Dilaksanakan'), ('ACKNOWLEDGED_AOCH', 'Acknowledged AOCH'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan')], max_length=30)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_status', to='pas.pengajuan')),
            ],
            options={
                'verbose_name': 'Riwayat Status',
                'verbose_name_plural': 'Riwayat Status',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DokumenPendamping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.PositiveSmallIntegerField()),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Pendamping')),
                ('file', models.FileField(upload_to='pengajuan/pendamping/')),
                ('status_verifikasi', models.CharField(choices=[('UPLOADED', 'Diunggah'), ('VALID', 'Valid'), ('INVALID', 'Tidak Valid')], default='UPLOADED', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendamping_verified', to=settings.AUTH_USER_MODEL)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendamping', to='pas.pengajuan')),
            ],
            options={
                'verbose_name': 'Dokumen Pendamping',
                'verbose_name_plural': 'Dokumen Pendamping',
                'ordering': ['urutan'],
                'constraints': [models.UniqueConstraint(fields=('pengajuan', 'urutan'), name='unique_pendamping_per_pengajuan')],
            },
        ),
    ]
