# Generated by Django 6.1.1 on 2026-09-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persyaratan',
            name='layanan',
        ),
        migrations.DeleteModel(
            name='DokumenPengajuan',
        ),
        migrations.DeleteModel(
            name='Persyaratan',
        ),
    ]
