# Generated by Django 6.1.1 on 2026-09-06 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0001_initial'),
        ('perusahaan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PengajuanPAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_pengajuan', models.CharField(blank=True, max_length=30, unique=True)),
                ('tanggal_pengajuan', models.DateField(auto_now_add=True)),
                ('tanggal_mulai', models.DateField(blank=True, null=True)),
                ('tanggal_berakhir', models.DateField(blank=True, null=True)),
                ('keperluan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('DOCUMENT_REVIEW', 'Review Dokumen'), ('REVISION_REQUIRED', 'Perlu Revisi'), ('ADMIN_APPROVED', 'Disetujui Admin'), ('WAITING_SCREENING', 'Menunggu Screening'), ('SCREENING_SCHEDULED', 'Screening Terjadwal'), ('SCREENING_PROCESS', 'Proses Screening'), ('SCREENING_PASSED', 'Lulus Screening'), ('SCREENING_FAILED', 'Tidak Lulus Screening'), ('WAITING_PAYMENT', 'Menunggu Pembayaran'), ('PAYMENT_PENDING', 'Pembayaran Pending'), ('PAYMENT_PAID', 'Pembayaran Lunas'), ('PAYMENT_FAILED', 'Pembayaran Gagal'), ('WAITING_APPROVAL', 'Menunggu Approval'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('PAS_ISSUED', 'PAS Diterbitkan'), ('EXPIRED', 'Kedaluwarsa'), ('CANCELLED', 'Dibatalkan')], default='DRAFT', max_length=30)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_akses', models.ManyToManyField(blank=True, related_name='pengajuan', to='pas.areaakses')),
                ('jenis_pas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pengajuan', to='pas.jenispas')),
                ('pemohon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan', to=settings.AUTH_USER_MODEL)),
                ('perusahaan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengajuan', to='perusahaan.perusahaan')),
            ],
            options={
                'verbose_name': 'Pengajuan PAS',
                'verbose_name_plural': 'Pengajuan PAS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DokumenPengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pengajuan/dokumen/')),
                ('nomor_dokumen', models.CharField(blank=True, max_length=100)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('status_verifikasi', models.CharField(choices=[('UPLOADED', 'Diunggah'), ('VALID', 'Valid'), ('INVALID', 'Tidak Valid'), ('REVISION_REQUIRED', 'Perlu Revisi')], default='UPLOADED', max_length=30)),
                ('catatan_verifikator', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('persyaratan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='pas.persyaratan')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumen_verified', to=settings.AUTH_USER_MODEL)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='pas.pengajuanpas')),
            ],
            options={
                'verbose_name': 'Dokumen Pengajuan',
                'verbose_name_plural': 'Dokumen Pengajuan',
                'ordering': ['persyaratan__urutan'],
            },
        ),
        migrations.CreateModel(
            name='StatusRiwayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('DOCUMENT_REVIEW', 'Review Dokumen'), ('REVISION_REQUIRED', 'Perlu Revisi'), ('ADMIN_APPROVED', 'Disetujui Admin'), ('WAITING_SCREENING', 'Menunggu Screening'), ('SCREENING_SCHEDULED', 'Screening Terjadwal'), ('SCREENING_PROCESS', 'Proses Screening'), ('SCREENING_PASSED', 'Lulus Screening'), ('SCREENING_FAILED', 'Tidak Lulus Screening'), ('WAITING_PAYMENT', 'Menunggu Pembayaran'), ('PAYMENT_PENDING', 'Pembayaran Pending'), ('PAYMENT_PAID', 'Pembayaran Lunas'), ('PAYMENT_FAILED', 'Pembayaran Gagal'), ('WAITING_APPROVAL', 'Menunggu Approval'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('PAS_ISSUED', 'PAS Diterbitkan'), ('EXPIRED', 'Kedaluwarsa'), ('CANCELLED', 'Dibatalkan')], max_length=30)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_status', to='pas.pengajuanpas')),
            ],
            options={
                'verbose_name': 'Riwayat Status',
                'verbose_name_plural': 'Riwayat Status',
                'ordering': ['-created_at'],
            },
        ),
    ]
