# Generated by Django 6.1.1 on 2026-09-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0002_remove_persyaratan_layanan_delete_dokumenpengajuan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuan',
            name='pic_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email PIC'),
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='pic_jabatan',
            field=models.CharField(blank=True, max_length=100, verbose_name='Jabatan PIC'),
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='pic_nama',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nama PIC'),
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='pic_no_hp',
            field=models.CharField(blank=True, max_length=20, verbose_name='No. HP PIC'),
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='pic_nomor_identitas',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nomor Identitas PIC'),
        ),
    ]
