# Generated by Django 6.1.1 on 2026-09-06 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0002_pengajuanpas_dokumenpengajuan_statusriwayat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PASCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_pas', models.CharField(blank=True, max_length=30, unique=True)),
                ('nomor_induk', models.CharField(blank=True, max_length=100)),
                ('tanggal_terbit', models.DateField(auto_now_add=True)),
                ('tanggal_berlaku', models.DateField(blank=True, null=True)),
                ('tanggal_expired', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('EXPIRED', 'Kedaluwarsa'), ('REVOKED', 'Dicabut')], default='ACTIVE', max_length=20)),
                ('qr_token', models.CharField(blank=True, max_length=80, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('jenis_pas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pas_cards', to='pas.jenispas')),
                ('pengajuan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pas_card', to='pas.pengajuanpas')),
            ],
            options={
                'verbose_name': 'Kartu PAS',
                'verbose_name_plural': 'Kartu PAS',
                'ordering': ['-tanggal_terbit'],
            },
        ),
    ]
