# Generated by Django 6.1.1 on 2026-09-24 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0003_pengajuan_pic_email_pengajuan_pic_jabatan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuan',
            name='pemohon_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Pemohon'),
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='pemohon_instansi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Instansi/Perusahaan Pemohon'),
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='pemohon_nama',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nama Pemohon'),
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='pemohon_no_hp',
            field=models.CharField(blank=True, max_length=20, verbose_name='No. HP Pemohon'),
        ),
        migrations.AlterField(
            model_name='pengajuan',
            name='pemohon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengajuan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pengajuan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DIAJUKAN', 'Diajukan'), ('VERIFIKASI_KOMERSIL', 'Verifikasi Komersil'), ('REVISI_PEMOHON', 'Revisi Pemohon'), ('DISETUJUI_KOMERSIL', 'Disetujui Komersil'), ('MENUNGGU_OPERASI', 'Menunggu Operasi'), ('DITOLAK_OPERASI', 'Ditolak Operasi'), ('DISETUJUI_OPERASI', 'Disetujui Operasi'), ('MENUNGGU_PEMBAYARAN', 'Menunggu Pembayaran'), ('DIBAYAR', 'Sudah Dibayar'), ('PAS_TERBIT', 'PAS Diterbitkan'), ('SIAP_DILAKSANAKAN', 'Siap Dilaksanakan'), ('DILAKSANAKAN', 'Dilaksanakan'), ('ACKNOWLEDGED_AOCH', 'Acknowledged AOCH'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='statusriwayat',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DIAJUKAN', 'Diajukan'), ('VERIFIKASI_KOMERSIL', 'Verifikasi Komersil'), ('REVISI_PEMOHON', 'Revisi Pemohon'), ('DISETUJUI_KOMERSIL', 'Disetujui Komersil'), ('MENUNGGU_OPERASI', 'Menunggu Operasi'), ('DITOLAK_OPERASI', 'Ditolak Operasi'), ('DISETUJUI_OPERASI', 'Disetujui Operasi'), ('MENUNGGU_PEMBAYARAN', 'Menunggu Pembayaran'), ('DIBAYAR', 'Sudah Dibayar'), ('PAS_TERBIT', 'PAS Diterbitkan'), ('SIAP_DILAKSANAKAN', 'Siap Dilaksanakan'), ('DILAKSANAKAN', 'Dilaksanakan'), ('ACKNOWLEDGED_AOCH', 'Acknowledged AOCH'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan')], max_length=30),
        ),
    ]
