# Generated by Django 6.1.1 on 2026-09-30 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0004_pengajuan_pemohon_email_pengajuan_pemohon_instansi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftarhitam',
            name='nik',
            field=models.CharField(blank=True, db_index=True, help_text='Kosongkan untuk blacklist berdasarkan nama saja.', max_length=50, verbose_name='NIK / No. Identitas'),
        ),
        migrations.AddField(
            model_name='dokumenpendamping',
            name='nik',
            field=models.CharField(blank=True, max_length=50, verbose_name='NIK / No. Identitas'),
        ),
        migrations.AddField(
            model_name='dokumenpendamping',
            name='nomor_pas',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Nomor PAS Visitor'),
        ),
        migrations.AddField(
            model_name='layanan',
            name='lokasi',
            field=models.CharField(choices=[('DEPARTURE', 'Departure'), ('ARRIVAL', 'Arrival')], db_index=True, default='ARRIVAL', max_length=20),
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='tanggal_berlaku_pas',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Tanggal Berlaku PAS'),
        ),
        migrations.CreateModel(
            name='SerahTerimaPAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BELUM', 'Belum Diserahkan'), ('DITERIMA', 'Sudah Diterima Pemohon'), ('DIKEMBALIKAN', 'Sudah Dikembalikan Pemohon')], default='BELUM', max_length=20)),
                ('penerima_nama', models.CharField(blank=True, max_length=255, verbose_name='Nama Penerima (PIC / Wakil)')),
                ('penerima_nik', models.CharField(blank=True, max_length=50, verbose_name='NIK Penerima')),
                ('penerima_jabatan', models.CharField(blank=True, max_length=100, verbose_name='Jabatan Penerima')),
                ('penerima_delegasi', models.CharField(blank=True, help_text='Diisi bila penyerahan diwakilkan oleh orang lain dari PIC pemohon.', max_length=255, verbose_name='Ditugaskan Kepada')),
                ('foto_penyerahan', models.ImageField(blank=True, null=True, upload_to='pas/serah_terima/foto/', verbose_name='Foto Penyerahan')),
                ('ttd_elektronik', models.ImageField(blank=True, null=True, upload_to='pas/serah_terima/ttd/', verbose_name='Tanda Tangan Elektronik')),
                ('tanggal_penyerahan', models.DateTimeField(blank=True, null=True)),
                ('tanggal_pengembalian', models.DateTimeField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pengajuan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='serah_terima', to='pas.pengajuan')),
            ],
            options={
                'verbose_name': 'Serah Terima PAS',
                'verbose_name_plural': 'Serah Terima PAS',
                'ordering': ['-updated_at'],
            },
        ),
    ]
