# Generated by Django 6.1.1 on 2026-09-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0007_serahterimapas_petugas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DIAJUKAN', 'Diajukan'), ('VERIFIKASI_KOMERSIL', 'Verifikasi Komersil'), ('REVISI_PEMOHON', 'Revisi Pemohon'), ('DISETUJUI_KOMERSIL', 'Disetujui Komersil'), ('MENUNGGU_OPERASI', 'Menunggu Operasi'), ('DITOLAK_OPERASI', 'Ditolak Operasi'), ('DISETUJUI_OPERASI', 'Disetujui Operasi'), ('MENUNGGU_PEMBAYARAN', 'Menunggu Pembayaran'), ('BUKTI_TERUNGGAH', 'Bukti Bayar Sudah Diunggah'), ('DIBAYAR', 'Sudah Dibayar'), ('PAS_TERBIT', 'PAS Diterbitkan'), ('SIAP_DILAKSANAKAN', 'Siap Dilaksanakan'), ('DILAKSANAKAN', 'Dilaksanakan'), ('ACKNOWLEDGED_AOCH', 'Acknowledged AOCH'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='statusriwayat',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DIAJUKAN', 'Diajukan'), ('VERIFIKASI_KOMERSIL', 'Verifikasi Komersil'), ('REVISI_PEMOHON', 'Revisi Pemohon'), ('DISETUJUI_KOMERSIL', 'Disetujui Komersil'), ('MENUNGGU_OPERASI', 'Menunggu Operasi'), ('DITOLAK_OPERASI', 'Ditolak Operasi'), ('DISETUJUI_OPERASI', 'Disetujui Operasi'), ('MENUNGGU_PEMBAYARAN', 'Menunggu Pembayaran'), ('BUKTI_TERUNGGAH', 'Bukti Bayar Sudah Diunggah'), ('DIBAYAR', 'Sudah Dibayar'), ('PAS_TERBIT', 'PAS Diterbitkan'), ('SIAP_DILAKSANAKAN', 'Siap Dilaksanakan'), ('DILAKSANAKAN', 'Dilaksanakan'), ('ACKNOWLEDGED_AOCH', 'Acknowledged AOCH'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan')], max_length=30),
        ),
    ]
