# Generated by Django 6.1.1 on 2026-10-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0009_backfill_bukti_terunggah'),
    ]

    operations = [
        migrations.AddField(
            model_name='serahterimapas',
            name='foto_pengembalian',
            field=models.ImageField(blank=True, null=True, upload_to='pas/serah_terima/foto/', verbose_name='Foto Pengembalian'),
        ),
        migrations.AddField(
            model_name='serahterimapas',
            name='ttd_pengembalian',
            field=models.ImageField(blank=True, null=True, upload_to='pas/serah_terima/ttd/', verbose_name='Tanda Tangan Pengembalian'),
        ),
    ]
