# Generated by Django 6.1.1 on 2026-10-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0010_serahterimapas_foto_pengembalian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuan',
            name='pic_npwp',
            field=models.CharField(blank=True, max_length=50, verbose_name='NPWP PIC'),
        ),
    ]
