# Generated by Django 6.1.1 on 2026-09-06 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perusahaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nib', models.CharField(blank=True, max_length=50, verbose_name='NIB')),
                ('npwp', models.CharField(blank=True, max_length=50, verbose_name='NPWP')),
                ('alamat', models.TextField(blank=True)),
                ('telepon', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pic', models.CharField(blank=True, max_length=255, verbose_name='PIC / Penanggung Jawab')),
                ('dokumen_legalitas', models.FileField(blank=True, null=True, upload_to='perusahaan/legalitas/')),
                ('status_aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perusahaan',
                'verbose_name_plural': 'Perusahaan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Pemohon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(blank=True, max_length=20, verbose_name='NIK')),
                ('nama_lengkap', models.CharField(blank=True, max_length=255)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('alamat', models.TextField(blank=True)),
                ('nomor_hp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('jabatan', models.CharField(blank=True, max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pemohon/foto/')),
                ('status_aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pemohon', to=settings.AUTH_USER_MODEL)),
                ('perusahaan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pemohon', to='perusahaan.perusahaan')),
            ],
            options={
                'verbose_name': 'Pemohon',
                'verbose_name_plural': 'Pemohon',
                'ordering': ['nama_lengkap'],
            },
        ),
    ]
